FitnessGuru/Models/FoodModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FitnessGuru.Models
{
    public class FoodModel
    {   [Column("FoodId")]
        public int Id { get; set; }
        public string FoodName { get; set; }
        public string ServingSize { get; set; }
        public float Calories { get; set; }
        public float Carbohydrate { get; set; }
        public float Fat { get; set; }
        public float Protein { get; set; }

    }
}

FitnessGuru/Controllers/FoodModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessGuru.Models;

namespace FitnessGuru.Controllers
{
    public class FoodModelsController : Controller
    {
        private FitnessDbCM db = new FitnessDbCM();

        // GET: FoodModels
        public ActionResult Index()
        {
            return View(db.Foods.ToList());
        }

        // GET: FoodModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodModel foodModel = db.Foods.Find(id);
            if (foodModel == null)
            {
                return HttpNotFound();
            }
            return View(foodModel);
        }

        // GET: FoodModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FoodModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FoodName,ServingSize,Calories,Carbohydrate,Fat,Protein")] FoodModel foodModel)
        {
            if (ModelState.IsValid)
            {
                db.Foods.Add(foodModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(foodModel);
        }

        // GET: FoodModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodModel foodModel = db.Foods.Find(id);
            if (foodModel == null)
            {
                return HttpNotFound();
            }
            return View(foodModel);
        }

        // POST: FoodModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FoodName,ServingSize,Calories,Carbohydrate,Fat,Protein")] FoodModel foodModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(foodModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(foodModel);
        }

        // GET: FoodModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodModel foodModel = db.Foods.Find(id);
            if (foodModel == null)
            {
                return HttpNotFound();
            }
            return View(foodModel);
        }

        // POST: FoodModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FoodModel foodModel = db.Foods.Find(id);
            db.Foods.Remove(foodModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search(string search)
        {                   
                return View(db.Foods.Where(x => x.FoodName.StartsWith(search) || search == null).ToList());
           
        }
    }
}

FitnessGuru/Views/FoodModels/Create.cshtml
@model FitnessGuru.Models.FoodModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FoodModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FoodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FoodName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FoodName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServingSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServingSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServingSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Carbohydrate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Carbohydrate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Carbohydrate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Protein, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Protein, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Protein, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FitnessGuru/Views/FoodModels/Delete.cshtml
@model FitnessGuru.Models.FoodModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FoodModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FoodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServingSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServingSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calories)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Carbohydrate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carbohydrate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Protein)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Protein)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FitnessGuru/Views/FoodModels/Details.cshtml
@model FitnessGuru.Models.FoodModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FoodModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FoodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServingSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServingSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calories)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Carbohydrate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carbohydrate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Protein)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Protein)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FitnessGuru/Views/FoodModels/Edit.cshtml
@model FitnessGuru.Models.FoodModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FoodModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FoodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FoodName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FoodName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServingSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServingSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServingSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Carbohydrate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Carbohydrate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Carbohydrate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Protein, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Protein, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Protein, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FitnessGuru/Views/FoodModels/Index.cshtml
@model IEnumerable<FitnessGuru.Models.FoodModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Search", "FoodModels", FormMethod.Get))
{
    //the following are search options
    <div class="form-group">
        <text>FoodName</text> @Html.TextBox("search") <input type="submit" name="submit" value="Search" class="btn btn-default" / >
    </div>

}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FoodName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServingSize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Calories)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Carbohydrate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Protein)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FoodName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServingSize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Calories)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Carbohydrate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Protein)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

FitnessGuru/Views/FoodModels/Search.cshtml
@model IEnumerable<FitnessGuru.Models.FoodModel>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FoodName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServingSize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Calories)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Carbohydrate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Protein)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FoodName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ServingSize)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Calories)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Carbohydrate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Protein)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>